# Project-wide Gradle settings.

# Specifying JVM memory args for Gradle Daemon to avoid GC thrashing
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# AndroidX support
android.useAndroidX=true

# Optimization flags for faster builds
org.gradle.parallel=true
org.gradle.caching=true
